version: '3.8'

# dir ../PatientApi
# docker-compose -f PatientApi.Web/docker-compose.yml up --build

services:
  # Db
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: MedicineDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Web API
  api:
    build:
      context: ..
      dockerfile: PatientApi.Web/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=MedicineDb;Username=postgres;Password=123
    depends_on:
      - db

volumes:
  postgres_data: